// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Számla.Data;

#nullable disable

namespace Számla.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20240327094229_teszt")]
    partial class teszt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Számla.Models.Class1", b =>
                {
                    b.Property<string>("nev")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("bevetel")
                        .HasColumnType("int");

                    b.Property<int>("kor")
                        .HasColumnType("int");

                    b.Property<string>("munka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("varos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nev");

                    b.ToTable("Class1");
                });
#pragma warning restore 612, 618
        }
    }
}
